### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mupsje** [vaproloff/tolerant-thermostat#1]
I will test it. 

one word:  Amazing!

Thank you so much!

Q:

Is there a way to code in package like:

```
climate:
  - platform: tolerant_thermostat
    name: "Heater Element Thermostat"
    target_sensor: sensor.boiler_return_temperature
    heater: switch.virtual_vw_element_01
    min_temp: 40
    max_temp: 60
    target_temp_high: 55
    target_temp_low: 45
```
Or only ad with intergrations?
